# Generated by Django 4.2.29 on 2026-03-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_by_stem',
            field=models.BooleanField(default=False, verbose_name='Продается поштучно'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (напр. Длина)')),
                ('value', models.CharField(max_length=100, verbose_name='Значение (напр. 60 см)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену для этого варианта', max_digits=10, verbose_name='Цена за 1 шт')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant', verbose_name='Вариант'),
        ),
    ]
